### ISSUE TITLE
APOR Calculator has a 404 error

### ISSUE THREAD

**Issue by hathor777** [cfpb/hmda-tools#9]
Greetings,

The APOR calculator page is receiving a 404 error. Please advise when this will be back up and running. We need this tool to test for compliance related issues.

**Comment by awolfe76** [comment]
Thanks, @hathor777. It's back up and running. You may notice some missing images, we're working on that now, but the tool itself is working.

**Comment by hathor777** [comment]
Thank you very much for your assistance! :-)

Jessica Carpenter
Home Loan Specialist III, Compliance
PennyMac Corporation
Corporate NMLS# 252869
jessica.carpenter@pnmac.com
(p) 813-498-0876
www.gopennymac.com

**Comment by hathor777** [comment]
My apologies for the muliple entries.. I wasn't sure which thread was the
most appropriate for the issue.

Jessica Carpenter
Home Loan Specialist III, Compliance
PennyMac Corporation
Corporate NMLS# 252869
jessica.carpenter@pnmac.com
(p) 813-498-0876
www.gopennymac.com
